# Generated by Django 5.1.1 on 2024-09-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_article_remove_feedbackrequest_company_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ExtraFields',
        ),
        migrations.DeleteModel(
            name='FeedbackRequest',
        ),
    ]
