# Generated by Django 5.1.1 on 2024-09-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_ingredient_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ('id',), 'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
    ]
