# Generated by Django 5.1.1 on 2024-09-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_recipestep_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-id',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
